### PR TITLE
Make pre-commit Git hook POSIX compliant and executable

### PR DESCRIPTION
**Pull request by Freso**
See individual commit messages for reasoning.

### CODE REVIEW

**Comment by WrinklyNinja** [comment]
This doesn't seem to have worked, because it's included a POT file with only the creation date changed. :confused:

**Comment by Freso** [comment]
Yeah, in the first of the two commits. Which is how I noticed the error in the hook script and made the second commit. I actually rebased it originally to remove the edit to the .pot, but I guess it snuck in again when I re-rebased it to fix a mistake in the `ln -s` call in the first commit's comment… I can re-re-rebase to remove the file, or it can stay in as a testament to the issue being fixed. :)

**Comment by WrinklyNinja** [comment]
Oh, so the `if` statement was always returning false in your shell?

I've tested your changes out and they work for me. :+1: Though I have discovered that the hook isn't executed if I commit through GitHub Desktop, because it isn't finding xgettext in my PATH, so now I've got to figure why its PATH is different...

**Comment by Freso** [comment]
> Oh, so the `if` statement was always returning false in your shell?

Yeah, exactly. And actually, on that note - it will probably be better to negate the checks. That is, use `!=` instead of `=` and `-o` instead of `-a`. That way, if the `test` fails for whatever reason, it will default to not update the .pot.

**Comment by Freso** [comment]
Hm. No. I guess that won't work the way I naïvely imagined it.

**Comment by Freso** [comment]
At half past ten in the evening I couldn't think of a way to do what I wanted to do without making the script significantly more complex. The script works now (for me :)), so merging it as it is now.

**Pull request merged**
