### PR TITLE
Update Brazilian Portuguese localization

### PR DESCRIPTION
**Pull request by DefinitelyNotGabi**
Grammar fixes and general improvements for better ptbr comprehension.

### CODE REVIEW

**Comment by sibir-ine** [comment]
Thanks for the localization updates @DefinitelyNotGabi! However, it doesn't look like you've updated the `loot.po` file against the template as there are ~100 new strings missing as well as ~50 obsolete strings present. If you're interested in fully updating LOOT's Brazilian Portuguese localization, you can read about how to do so [here](https://github.com/loot/loot/blob/master/CONTRIBUTING.md#translating-the-loot-application). Also, just FYI, anything starting with `#~` isn't used in the app anymore & doesn't need to be updated. If you update the file using Poedit, those strings will be ignored.

The [prelude](https://github.com/loot/prelude/blob/v0.18/prelude.yaml), which contains translations for messages used exclusively by the masterlists, is also missing 8 Brazilian Portuguese translations if you're interested in taking a look at them too.

**Comment by sibir-ine** [comment]
I just rememberd, Kyo-- from the [Discord](https://discord.com/channels/473542112974077963/805162627860398131/1035973871226069142) also provided an updated Brazilian Portuguese `loot.po` a little while ago. You can work from it & review & update it if necessary if you'd like.

[loot.zip](https://github.com/loot/loot/files/10249960/loot.zip)

**Comment by DefinitelyNotGabi** [comment]
Hi! How are you? I hope you are good c:

I'm so sorry for taking long to reply. Got some problems with my PC caused by an electrical fault. I expect to fix everything by Sunday, and then I'll take a look at this new file.

Oh and I didn't know about the new template, since I opened this GitHub and didn't found instructions besides how we were supposed to push commits.

As a feedback, if you wouldn't mind, I recommend you adding some info for translators looking for updating (or translating into a new language). Maybe a step-by-step or something simple, just so that you don't have to worry about correcting pushes made for outdated versions.

:p

**Comment by sibir-ine** [comment]
No worries! I linked this earlier, but we have a section for translators in our Contributing readme with step-by-step instructions that I linked earlier ([here](https://github.com/loot/loot/blob/master/CONTRIBUTING.md#translating-the-loot-application) it is again for convenience), but let us know if you still have questions or concerns.

**Comment by pStyl3** [comment]
@DefinitelyNotGabi 
Hey, I just wanted to mention that the next LOOT version will be released in a couple of days. Do you think that you could update the brazilian portuguese translation until then?

**Comment by Ortham** [comment]
Closing this because the pt_BR localisation was just updated in #1858. If there are any differences that you think are significant, please do submit this again once it's been updated to the match the latest template.

**Pull request closed without merging**
