### PR TITLE
Full Ukrainian translation + small update to Russian translation

### PR DESCRIPTION
**Pull request by IllusiveMan196**

### CODE REVIEW

**Comment by IllusiveMan196** [comment]
Ok, I don't know why but it times out even when everything looks fine... 10 min of "testing" and it just times out or "cancelled by user".

**Comment by Ortham** [comment]
> 
> 
> Ok, I don't know why but it times out even when everything looks fine... 10 min of "testing" and it just times out or "cancelled by user".
> Anyhow, new translation is in there, folders are appropriately named, installer has relevant new language added, test scripts as well.

I've been cancelling them because you've pushed several times in quick succession and continuing to build old commits is just putting pointless load on the CI infrastructure.

**Comment by IllusiveMan196** [comment]
Understood, now it should be fine.

**Comment by IllusiveMan196** [comment]
Yeah, now it's fine, green checkmarks everywhere :)

**Pull request merged**
