### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [LOOT/LOOT](https://hosted.weblate.org/projects/loot/loot/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by pStyl3** [comment]
Currently this PR changes the `Last-Translator` line within the different `loot.po` files, ideally we should avoid changing these, or restore them after the "general cleanup".

I would also suggest to update every `loot.po` file with `template.pot` and use Poedit's `purge deleted translations` feature each time. Though that likely should happen with another PR.

**Comment by Ortham** [comment]
> Currently this PR changes the `Last-Translator` line within the different `loot.po` files, ideally we should avoid changing these, or restore them after the "general cleanup".

I think that's just because I went through the issues Weblate raised and fixed a bunch of them, if someone else makes a change then it'll be them mentioned there, so that seems to be working as we'd want, isn't it?

> I would also suggest to update every loot.po file with template.pot and use Poedit's purge deleted translations feature each time. Though that likely should happen with another PR.

It looks like it's possible to do the former in Weblate using [an add-on](https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-gettext-msgmerge): I'll enable it and see what happens.

**Comment by pStyl3** [comment]
> if someone else makes a change then it'll be them mentioned there, so that seems to be working as we'd want, isn't it?

Yes, it's just that I thought that it wouldn't be ideal if the `Last Translator` is getting changed because of some general maintenance.

**Comment by Ortham** [comment]
> Yes, it's just that I thought that it wouldn't be ideal if the `Last Translator` is getting changed because of some general maintenance.

Oh, I understand now.

---

Well, that add-on certainly made a lot of changes. There's a lot of noise from changing line numbers and c++-format tags getting stripped (my guess is that Weblate is using an older version of gettext, it's not a big deal beyond the noise though), and it defaulted to allowing fuzzy matching which has caused some incorrect matches that I've spotted, so I've disabled that.

It updates the PO files whenever the POT file in this repo changes, so if that update introduces changes and they trigger a PR back to this repo with those changes then I think that would be fine, but if it's going to hang onto those changes until there is a translation change and then open a PR for those changes together than that'll be more difficult to review.

I couldn't see an option to delete old translations from the PO files, so it seems like we'll have to do that manually.

**Comment by Ortham** [comment]
There is also the option to reset the Weblate repository state to match this repo, so if we make manual changes we can force that reset afterwards - we'd lose the queued up changes I've been making so far, but that's not a big deal (I can redo them as part of the manual changes).

I'd like to reset the repo state to test out if PO file sync changes are held back until a translation is made, but I won't do that just yet.

**Comment by Ortham** [comment]
I updated the PO files and applied the fixes I made in Weblate directly in this repository, and now Weblate has alerted that its repo is locked due to a merge conflict with this repo. The alert displays instructions for resolving the issue, which boils down to adding weblate as another remote to a local clone of this repo, then merging in the weblate changes and pushing them to this repo, and then weblate will stop seeing conflicts. However, that's not what I want to do in this case: I'd rather resolve conflicts by rebasing weblate on top of this repo, but I'm not able to push the rebased branch to the weblate repo. As such, I'm just going to reset the weblate repo to match this one, losing all the changes I've made in Weblate so far (which unfortunately will include what strings are approved, I think).

I've also installed the "Customise gettext output" add-on to configure line wrapping to the xgettext default of 77 characters, to hopefully reduce the noise in Weblate's changes.

**Comment by Ortham** [comment]
Just noting that this ties back to loot/loot#1973.

**Comment by Ortham** [comment]
Closing this as it's now outdated.

**Pull request closed without merging**
