### PR TITLE
Updated Bulgarian Translation Again

### PR DESCRIPTION
**Pull request by RacerBG**
Here we go again... :smiley:

### CODE REVIEW

**Comment by Ortham** [comment]
Ah, those message placeholders should have numbers in them (only for consistency in this case), I'll fix that later and can you then update the translation?

**Comment by RacerBG** [comment]
> Ah, those message placeholders should have numbers in them (only for consistency in this case), I'll fix that later and can you then update the translation?

Sure!

**Comment by Ortham** [comment]
@RacerBG I've just updated the master branch, can you update your translation to match?

**Comment by RacerBG** [comment]
> @RacerBG I've just updated the master branch, can you update your translation to match?

Should be good to go.

**Comment by Ortham** [comment]
Thanks!

**Pull request merged**
