### PR TITLE
Added Japanese Translation & Language

### PR DESCRIPTION
**Pull request by kuroko137**
I added Japanese Translation and Language.
Translation is completely done, but I'm not sure if it will work properly because I have not tested it.
(I have only tested my loot.mo by renaming a loot.mo for other languages.)

### CODE REVIEW

**Comment by kuroko137** [comment]
I did Revert without knowing well what it is.
I'll try to learn more about using Git, and I'll use other commands from next time.
Please close this PR if necessary.

Freso, thank you for your explanation!

**Comment by Freso** [comment]
It's not necessary to close this PR for now. You can `git push --force` changes to your branch and they'll be reflected in the PR here. :)

**Comment by WrinklyNinja** [comment]
The AppVeyor build failure is due to PRs not having access to secure env vars (which I guess I can fix with a check if it's a PR), the Travis failure may be due to their recent environment upgrade.

I'll run a build locally to check that everything is in order.

**Comment by WrinklyNinja** [comment]
👍

**Comment by kuroko137** [comment]
Thanks WrinklyNinja! Your new build works perfectly.

**Pull request merged**
