### PR TITLE
Update to Korean language support (0.7 to 0.14.0)

### PR DESCRIPTION
**Pull request by steamb23**
Hi. It's been a very long time.
I received translation-related mentions via email and modified some translations to fit the latest version.
Unfortunately, no other Koreans have contributed to the translation of LOOT in the years that I quit my interest in Bethesda games.
This is very sad.

I am not able to contribute often to the translation project due to the work I am currently working on, but if I can afford it, I will help. 

I haven't used your LOOT for a long time, so I don't know exactly how it will appear, but I've only translated it so that it is possible to infer some meaning from Korean users. I hope there will be better contributors. :)

### CODE REVIEW

**Comment by sibir-ine** [comment]
@steamb23 Thank you so much! It's not a big deal, but the current version of LOOT is actually 0.16.0; would you mind updating the file to reflect that?

Also, I understand your busy so please take your time, but would you also be interested in localizing the messages in the masterlists as well? If you'd like to join the [Discord server](https://loot.github.io/discord/), there's a dedicated translations channel with a spreadsheet that contains all the strings to translate, & you can just add or update translations within it easily. If you don't have a Discord, I can provide you with a [copy](https://github.com/loot/loot/files/6176397/Masterlist_Localizations_v9.xlsx) & you could upload a completed spreadsheet in a comment on loot/loot.github.io#77.

**Comment by steamb23** [comment]
> @steamb23 Thank you so much! It's not a big deal, but the current version of LOOT is actually 0.16.0; would you mind updating the file to reflect that?
> 
> Also, I understand your busy so please take your time, but would you also be interested in localizing the messages in the masterlists as well? If you'd like to join the [Discord server](https://loot.github.io/discord/), there's a dedicated translations channel with a spreadsheet that contains all the strings to translate, & you can just add or update translations within it easily. If you don't have a Discord, I can provide you with a [copy](https://github.com/loot/loot/files/6176455/Masterlist_Localizations_v10.xlsx) & you could upload a completed spreadsheet in a comment on [loot/loot.github.io#77](https://github.com/loot/loot.github.io/issues/77).

Oh, the version I specified in the commit message is the version based on the latest master branch's translation files (POT and PO files).

Any text changed since 0.14.0?

**Comment by sibir-ine** [comment]
> Oh, the version I specified in the commit message is the version based on the latest master branch's translation files (POT and PO files).

Ah, I see what you mean. I'd still set it to 0.16.0 to avoid confusion since you're translating for 0.16.0.

> Any text changed since 0.14.0?

Possibly, @Ortham has anything changed that would warrant rebuilding the template? Or is that automatically taken care of?

**Comment by Ortham** [comment]
> Possibly, @Ortham has anything changed that would warrant rebuilding the template? Or is that automatically taken care of?

The template is supposed to be automatically kept up to date by a Git pre-commit hook, but the hook needs to be set up manually, and I just found that mine isn't for some reason, so the template is outdated. However, there are only a handful of differences (excluding source line number changes). I could probably add a CI check to see if the file is up to date or not, I'll file an issue about that.

I've got a branch with the updated template that I'll merge shortly.

**Comment by Ortham** [comment]
The template in the master branch is now up to date.

**Comment by sibir-ine** [comment]
@Ortham Thank you so much!

@steamb23 Can you please rebase & update your localization file again? There are 6 strings that need to be updated.

**Comment by pStyl3** [comment]
@steamb23 
Should we merge this PR as is? I think it would be better to merge these translations now, and add the missing ones, once steamb23 (or someone else) has the time to work on it.

**Comment by steamb23** [comment]
I will close this template to apply the next version of the template.

**Pull request closed without merging**
