### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by silentdark**

### CODE REVIEW

**Comment by sibir-ine** [comment]
It doesn't look like you synced your fork, it says it's 120 commits behind.

**Comment by silentdark** [comment]
There is no problem with fork sync. The Chinese translation has not been updated for a long time. After updating from the current version template, it may be a bit different from the previous translation file.

**Comment by silentdark** [comment]
Or do you mean create a new translation file from the current version template?

**Comment by sibir-ine** [comment]
This is from your fork:

image

Many changes were made to the template in those 120 commits. Some changes were even made to the Chinese `loot.po` (specifically changing the placeholders to a different format), resulting in conflicts that prevent GitHub from being able to merge your PR. You can read about syncing your fork [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork). Then, once you do that, you can update your `loot.po` with the template again & update the translation.

**Comment by silentdark** [comment]
I understand, the synchronization is indeed not successful, I will try again.

**Pull request closed without merging**
