### PR TITLE
minor fixes for japanese translation

### PR DESCRIPTION
**Pull request by kuroko137**

### CODE REVIEW

**Comment by kuroko137** [comment]
Sorry. I will do later.

**Comment by Freso** [comment]
Why did you close this? The PR looks good.

**Comment by kuroko137** [comment]
I was afraid that appveyor and Travis CI check error again, so I closed this PR.
The PR has been reopened now. I would be happy if you could commit.

**Comment by WrinklyNinja** [comment]
You can ignore the errors until I get around to fixing them.

**Pull request merged**
