### PR TITLE
Update fr loot.po

### PR DESCRIPTION
**Pull request by cpasmoi**

### CODE REVIEW

**Comment by cpasmoi** [comment]
"A cleaning guide is available here." is not translatable in the ui

**Comment by Freso** [comment]
@WrinklyNinja I'm not sure if it's a network error or a missing dependency in `.travis.yml` that's making this fail.

@cpasmoi I've reported that as #532.

**Comment by WrinklyNinja** [comment]
Reading the Travis docs, connections to Sauce Labs (which is what the JS tests run on) aren't allowed for PRs for security reasons.

@cpasmoi: Can you push another commit to this PR's branch, editing [line 61 of `.travis.yml`](https://github.com/loot/loot/blob/1af3bc9a9a10c831d3217742eeb45318c9748a27/.travis.yml#L61) to replace `npm test` with `'[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm test || false'`?

According to the Travis docs, that should disable the failing tests.

**Comment by cpasmoi** [comment]
not sure what you want,  https://github.com/loot/loot/pull/533 ? :ghost:

**Comment by WrinklyNinja** [comment]
Sure, whatever. I was just trying to make things easier for you...

**Pull request closed without merging**
