### PR TITLE
Updated russian localization from latest template

### PR DESCRIPTION
**Pull request by TokcDK**
String "You have not yet applied or cancelled your %s. Are you sure you want to quit?" was translated like "Операция \"%s\" все еще не применена\отменена. Действительно хотите выйти?" because %s have plural forms and was incorrect translation before it. It is on english like "Operation \"%s\" still not yet applied or cancelled. Are you sure you want to quit?"".
Also translated all new lines and new lines with plural forms.
loot.po was updated from template.pot(051216) before translation, translated, checked and saved.

### CODE REVIEW

**Comment by WrinklyNinja** [comment]
Well that's great, when msgfmt fails it prints my GitHub, Bintray and Sauce Labs access tokens. Now to invalidate them and re-generate and re-encrypt them...

The actual failure is

```
Error: Command failed: msgfmt resources/l10n/ru/LC_MESSAGES/loot.po -o resources/l10n/ru/LC_MESSAGES/loot.mo
resources/l10n/ru/LC_MESSAGES/loot.po:96:46: invalid control sequence
```

can you fix that?

**Comment by WrinklyNinja** [comment]
Right, GitHub, Bintray and Sauce Labs tokens have been revoked, and I've generated new tokens, but haven't yet updated the appveyor and travis configs in this repo and the loot-api-python repo with their encrypted values, so CI will fail until I do that.

**Comment by TokcDK** [comment]
Yes, I see. It is must be because '\ ' not '/' between words in the changed sentense with plural form of %s,

**Comment by TokcDK** [comment]
Can you give me link to the latest snapshot build for translation tests? Also some of messages on the first run window still have no strings for translation.

**Comment by TokcDK** [comment]
About LOOT window also not translatable.

**Comment by WrinklyNinja** [comment]
Can you rebase your PR branch off the latest `dev` to get the new auth tokens so that CI will pass?

> Can you give me link to the latest snapshot build for translation tests? 

Not yet, builds don't seem to be working properly since the tokens changed...

>Also some of messages on the first run window still have no strings for translation.

>About LOOT window also not translatable.

Which is why #664 is still open, no need to repeat yourself.

**Comment by TokcDK** [comment]
Need to make request again?

**Comment by WrinklyNinja** [comment]
No, just rebase your branch and force-push it, and the PR will update.

**Comment by TokcDK** [comment]
Too late.) Found one typo and fixed it.

**Comment by WrinklyNinja** [comment]
> Can you give me link to the latest snapshot build for translation tests?

You don't actually need a snapshot build, there haven't been any relevant changes since v0.10.2's release, so just use that.

**Comment by WrinklyNinja** [comment]
Please rebase on dev now.

**Comment by TokcDK** [comment]
Still problems with online checks?
I checked loot.mo from this translation with version 10.0.2 and he work perfectly without any problems.

**Comment by WrinklyNinja** [comment]
You haven't rebased yet, they'll fail until you've got the new auth tokens.

**Comment by TokcDK** [comment]
I need to change base:dev to other? To dev:master?

**Comment by WrinklyNinja** [comment]
No,

```
git checkout TokcDK-l10nRU-patch-1
git rebase dev
git push --force
```

please.

**Comment by TokcDK** [comment]
There is one problem. Im not using GIT and have no installed GIT. I made pull request with Web. Early when it was possible to change and update loot.po using repositories I just used TortoiseSVN for updates. Now when no access Im simple using file uploading with pull request on the "https://github.com/loot/loot/tree/dev/resources/l10n/ru/LC_MESSAGES".

Maybe simple make new pull request? Will it work like rebase?

**Comment by WrinklyNinja** [comment]
Oh, in that case I'll do the rebase for you.

**Pull request merged**
