### PR TITLE
Create loot.po in Swedish (sv)

### PR DESCRIPTION
**Pull request by Lakrits**
Translation into Swedish (sv) of LOOT, based on v.0.9.2. Including folders (.../resources/l10n/ sv/LC_MESSAGES/*).

### CODE REVIEW

**Comment by Freso** [comment]
Tack!

You may want to look into translating the installer and other areas not included by the .po file; see https://github.com/loot/loot/blob/dev/CONTRIBUTING.md#translating-loot for more information.

**Comment by WrinklyNinja** [comment]
Thanks, @Lakrits! As this is a new language, it'll also need code changes before LOOT will pick it up. I can do them, but you might also want to update the translation to match the latest template.pot, since you say you worked off v0.9.2.

**Comment by Freso** [comment]
I was actually considering doing them. Let's get all the Scandinavian languages in! :p

**Comment by WrinklyNinja** [comment]
I've just noticed the contributing guide is actually a bit out of date, which isn't very helpful... Fixing that now.

**Comment by WrinklyNinja** [comment]
@Freso I'll leave the code changes to you then.

**Comment by WrinklyNinja** [comment]
> The file name was by mistake set to LC_MESSAGES. It should be .../LC_MESSAGES/loot.po.

Fixed, and I've made the necessary code changes too.

**Pull request merged**
