### PR TITLE
Adding Portuguese (pt_PT) Translation For LOOT (#1434)

### PR DESCRIPTION
**Pull request by ironmagician**

### CODE REVIEW

**Comment by Ortham** [comment]
Thanks for these. The build is failing because I need to fix our CI setup, but I've been having trouble getting it to cache Boost... This will need rebasing once it's fixed, I'll let you know when that is.

**Comment by Ortham** [comment]
@ironmagician I've fixed the build, please rebase this on the `master` branch.

**Comment by ironmagician** [comment]
@Ortham all done here.

**Comment by Ortham** [comment]
Ah, the build is still failing because there's a test that needs updating for the new language: can you add a line for `pt_PT` under the `pt_BR` one [here](https://github.com/loot/loot/blob/master/src/tests/gui/state/loot_settings_test.h#L176-L178)?

**Comment by Ortham** [comment]
Thanks!

**Comment by sibir-ine** [comment]
> 
> 
> Ah, the build is still failing because there's a test that needs updating for the new language: can you add a line for `pt_PT` under the `pt_BR` one [here](https://github.com/loot/loot/blob/master/src/tests/gui/state/loot_settings_test.h#L176-L178)?

Should this be discussed in CONTRIBUTING.md under "Adding a New Translation"?

**Comment by ironmagician** [comment]
> Should this be discussed in CONTRIBUTING.md under "Adding a New Translation"?

I find that adding that would make the process more straight forward, yes.

A good solution was also to add my commit (or another similar translation commit) as an example, since it shows all needed changes.

**Comment by Ortham** [comment]
> @Ortham Should this be discussed in CONTRIBUTING.md under "Adding a New Translation"?

Yes, I'll do that.

> A good solution could be also to add my commit (or another similar translation commit) as an example, since it shows all needed changes. An extra upon the described steps, of course.

I'll do that too.

**Pull request merged**
